api:
    resource: "@WidgetInvitationBundle/Controller/API"
    type:     annotation
    prefix:   /api

backend_api:
    resource: "@WidgetInvitationBundle/Controller/BackendAPI"
    type:     annotation
    prefix:   /admin/api
