module.exports =
  components:
    'loading': require "components/backendbase/partial/loading.vue"
    'edit-manage': require "components/backendbase/partial/edit/manage.vue"
    'edit-input': require "components/backendbase/partial/edit/input.vue"
    'edit-html': require "components/backendbase/partial/edit/html.vue"
    'edit-groupselector': require "components/backendbase/partial/edit/groupselector.vue"
    'edit-selector': require "components/backendbase/partial/edit/selector.vue"
    'edit-textarea': require "components/backendbase/partial/edit/textarea.vue"
    'edit-switch': require "components/backendbase/partial/edit/switch.vue"
    'edit-password': require "components/backendbase/partial/edit/password.vue"
    'edit-repeated': require "components/backendbase/partial/edit/repeated.vue"
    'edit-photos': require "components/backendbase/partial/edit/photos.vue"
    'edit-choice': require "components/backendbase/partial/edit/choice.vue"
    'edit-number': require "components/backendbase/partial/edit/number.vue"
    'edit-date': require "components/backendbase/partial/edit/date.vue"
    'edit-datetime': require "components/backendbase/partial/edit/datetime.vue"
    'edit-checkboxgroup': require "components/backendbase/partial/edit/checkboxgroup.vue"