rules =
  'menu.siteuser': true
  'menu.sitegroup': true
  'menu.widget_shipment_config': true
  'menu.widget_payment_config': true
  'menu.widget_order_config': true
  'menu.widget_member_config': true
  'menu.system_config': true
  'menu.photoconfig': true
  'menu.orderstatus': true
  'menu.operation_log': true
  'menu.mail': true
  'menu.stock': false
  'menu.stock_style': false
  'menu.styletemplate': false
  'menu.productcategory': true
  'menu.product': true
  'menu.payment': true
  'menu.order': true
  'menu.member': true
  'menu.group': true
  'menu.discount_targetamount': true
  'menu.discount_shipment': true
  'menu.discount_product': true
  'menu.discount_percentage': true
  'menu.discount_group_list': true
  'menu.discount_coupon': true
  'menu.contactus': true
  'menu.categoryarticles_category': true
  'menu.categoryarticle': true
  'menu.bannercategory': true
  'menu.banner': true
  'menu.article': true
module.exports = rules