Widget\InvitationBundle\Model\Invitation:
    virtual_properties:
        getId:
            groups:
                -                   list
                -                   detail
            serialized_name:        id
        getName:
            groups:
                -                   list
                -                   detail
            serialized_name:        name
        getNickName:
            groups:
                -                   detail
            serialized_name:        nickname
        getPhone:
            groups:
                -                   list
                -                   detail
            serialized_name:        phone
        getNumberOfPeople:
            groups:
                -                   list
                -                   detail
            serialized_name:        number_of_people
        getAddress:
            groups:
                -                   detail
            serialized_name:        address
        getEmail:
            groups:
                -                   detail
            serialized_name:        email
        getAttend:
            groups:
                -                   list
                -                   detail
            serialized_name:        attend
        getKnownFrom:
            groups:
                -                   list
                -                   detail
            serialized_name:        known_from
        getNumberOfVegetarian:
            groups:
                -                   detail
            serialized_name:        number_of_vegetarian
        getNumberOfBabySeat:
            groups:
                -                   detail
            serialized_name:        number_of_baby_seat
        getNote:
            groups:
                -                   detail
            serialized_name:        note
        getCreatedAt:
            groups:
                -                   detail
            serialized_name:        created_at
        getUpdatedAt:
            groups:
                -                   detail
            serialized_name:        updated_at
        getCategories:
            groups:
                -                   list
                -                   detail
            serialized_name:        categories
        getIsSentEmail:
            groups:
                -                   list
                -                   detail
            serialized_name:        is_sent_email
        getIsSentAddress:
            groups:
                -                   list
                -                   detail
            serialized_name:        is_sent_address